export const CREATE_AGENT_SUCCESS = 'CREATE_AGENT_SUCCESS';
export const CREATE_AGENT_FAILURE = 'CREATE_AGENT_FAILURE';
export const LIST_AGENT_FAILURE = 'LIST_AGENT_FAILURE';
export const LIST_AGENT_SUCCESS = 'LIST_AGENT_SUCCESS'